name: Setup Sapfire CLI
description: Sets up Sapfire CLI

inputs:
  version:
    description: 'Which CLI version to use, defaults to latest release.'
    required: false
    default: latest

runs:
  using: "composite"
  steps:
  - name: Detect platform
    id: platform
    shell: bash
    run: |
      if [ "$RUNNER_OS" = "Linux" ]; then
        echo "host=linux" >> $GITHUB_OUTPUT
      elif [ "$RUNNER_OS" = "Windows" ]; then
        echo "host=win" >> $GITHUB_OUTPUT
      elif [ "$RUNNER_OS" = "macOS" ]; then
        echo "host=mac" >> $GITHUB_OUTPUT
      fi

  - name: Download
    uses: robinraju/release-downloader@v1.10
    with:
      repository: sapfire-sdk/cli
      latest: ${{ inputs.version == 'latest' }}
      tag: ${{ inputs.version != 'latest' && inputs.version || '' }}
      fileName: '*-${{ steps.platform.outputs.host }}.zip'
      tarBall: false
      zipBall: false
      out-file-path: "my-epic-sapfire-cli"

  - name: Setup
    shell: bash
    run: |
      7z x "my-epic-sapfire-cli/*-${{ steps.platform.outputs.host }}.zip" -omy-epic-sapfire-cli
      chmod +x my-epic-sapfire-cli/sapfire
      echo "$GITHUB_WORKSPACE/my-epic-sapfire-cli" >> $GITHUB_PATH
