# Update cli manifest in sapfire-sdk/homebrew-sapfire
# TODO: update the winget one too :P
name: Update CLI Manifests

on:
  # trigger when a new release is released
  release:
    types:
      - released
  
  workflow_dispatch: 

jobs:
  trigger:
    name: Update homebrew repo
    runs-on: ubuntu-latest
    steps:
    - name: Checkout homebrew tap
      uses: actions/checkout@v4
      with:
        repository: sapfire-sdk/homebrew-sapfire
        path: homebrew-sapfire
        token: ${{ secrets.SAPFIRE_BOT_PUSH_BIN_TOKEN }}

    - name: Fetch release info
      uses: actions/github-script@v6
      id: fetch-mac-release
      with:
        result-encoding: string
        script: |
          let rel = await github.rest.repos.getLatestRelease({
            owner: 'sapfire-sdk',
            repo: 'cli',
          });

          for (let asset of rel.data.assets) {
            if (asset.name.endsWith('-mac.zip')) {
              return asset.browser_download_url;
            }
          }

    - name: Update mac homebrew repo
      shell: bash
      run: |
        URL="${{ steps.fetch-mac-release.outputs.result }}"
        SAPFIRE_HASH=$(curl -L $URL | sha256sum | awk '{print $1}')
        cd homebrew-sapfire/Formula
        cp sapfire-cli.rb.in sapfire-cli.rb
        sed -i -e "s|DOWNLOAD_URL|$URL|g" sapfire-cli.rb
        sed -i -e "s/HASH/$SAPFIRE_HASH/g" sapfire-cli.rb

    - name: Push to repo
      shell: bash
      working-directory: ${{ github.workspace }}/homebrew-sapfire
      run: |
        git config --local user.email "${{ secrets.SAPFIRE_BOT_EMAIL }}"
        git config --local user.name "SapfireBot"
        git add .
        git commit -m "Update CLI"
        git remote set-url origin "https://SapfireBot:${{ secrets.SAPFIRE_BOT_PUSH_BIN_TOKEN }}@github.com/sapfire-sdk/homebrew-sapfire.git"
        git push || true
